# Generated by Django 5.2.7 on 2025-11-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
